### PR TITLE
Add Valkey support to the build and to the compatibility test in CI

### PR DESCRIPTION
**Pull request by bjosv**
Adds the CMake option `TEST_WITH_VALKEY_VERSION` to enable `make start` to setup Valkey clusters instead of Redis.
The default behavior, when the option is not set, is to run tests with Redis, but a given Valkey version takes precedence.

(Note: There is already an option to specify a Redis version `TEST_WITH_REDIS_VERSION` and Redis `6.2.1` is the default.)

Example usage:
```
mkdir build && cd build
cmake -DTEST_WITH_VALKEY_VERSION=7.2.5 ..

make start   # Start valkey clusters 
make test    # Tests run on valkey clusters
make stop    # Stop valkey clusters
```

Additionallty adds Valkey `7.2.5` to the compatibility test in CI.

### CODE REVIEW

**Comment by zuiderkwast** [comment]
Shall we leave this open until the next release candidate, or the actual release, is out?

**Comment by bjosv** [comment]
I guess you know best how far away an actual release is, and I've seen talks about possibly changing which patch-version to use.
The only benefit to merge it before could be to get the script in place to tryout more, and locally run towards unstable now and then..

**Comment by zuiderkwast** [comment]
ok, do as you want.

the release is within a week.

**Comment by bjosv** [comment]
Updated to run on the first stable release of Valkey `7.2.5`.

**Review by zuiderkwast — APPROVED** [review]

**Pull request merged**
